package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AndroidDebug'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AndroidDebug")) {
    params {
        expect {
            select("Mode", "Mode",
                    options = listOf("Debug", "Release"))
        }
        update {
            select("Mode", "Mode", display = ParameterDisplay.PROMPT,
                    options = listOf("Debug", "Release"))
        }
    }
}
